package graphicdiff;

import model.Model;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 * View knows only about Model
 * @author Luke
 */
public class View extends JFrame {

    Model model;
    /**
     * Creates new form GUI
     */
    public View() {
        initComponents();
    }
    
    public View(Model model) {
        initComponents();
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        browse = new javax.swing.JButton();
        seperator1 = new javax.swing.JPanel();
        right = new javax.swing.JButton();
        seperator2 = new javax.swing.JPanel();
        left = new javax.swing.JButton();
        seperator3 = new javax.swing.JPanel();
        jumpFormPanel = new javax.swing.JPanel();
        jumpField = new javax.swing.JTextField();
        skip = new javax.swing.JButton();
        editorPanePanels = new javax.swing.JPanel();
        scrollPane1 = new javax.swing.JScrollPane();
        clonePane1 = new javax.swing.JEditorPane();
        scrollPane2 = new javax.swing.JScrollPane();
        clonePane2 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        // Set layout for west pane (Buttons and stuff)
        leftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("CloneDiff - Luke Coy"));
        leftPanel.setLayout(new java.awt.GridLayout(10, 1));

        browse.setText("Browse (CSV)");
        
        leftPanel.add(browse);
        
        leftPanel.add(seperator1);
        
        right.setText("->");
        leftPanel.add(right);

        leftPanel.add(seperator2);
        
        left.setText("<-");
        leftPanel.add(left);

        leftPanel.add(seperator3);
        
        jumpFormPanel.setLayout(new java.awt.GridLayout(1, 2));
        jumpFormPanel.add(jumpField);
        skip.setText("Jump to it!");
        jumpFormPanel.add(skip);
        leftPanel.add(jumpFormPanel);
        
        getContentPane().add(leftPanel, java.awt.BorderLayout.LINE_START);
        editorPanePanels.setLayout(new java.awt.GridLayout(1, 2));
        scrollPane1.setViewportView(clonePane1);
        editorPanePanels.add(scrollPane1);
        scrollPane2.setViewportView(clonePane2);
        editorPanePanels.add(scrollPane2);
        getContentPane().add(editorPanePanels, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void appear() {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
       this.pack();
       this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel editorPanePanels;
    private javax.swing.JPanel seperator1;
    private javax.swing.JPanel seperator2;
    private javax.swing.JPanel seperator3;
    private javax.swing.JPanel jumpFormPanel;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTextField jumpField;
    private javax.swing.JButton left;
    private javax.swing.JEditorPane clonePane1;
    private javax.swing.JEditorPane clonePane2;
    private javax.swing.JButton right;
    private javax.swing.JButton skip;
    // End of variables declaration//GEN-END:variables

    public void setPanel1(String s) {
        clonePane1.setText(s);
    }
    
    public void setPanel2(String s) {
        clonePane2.setText(s);
    }
    
    public String getSkipField() {
        return jumpField.getText();
    }
    
    void addBrowseListener(ActionListener list) {
        browse.addActionListener(list);
    }
    
    void addRightListener(ActionListener list) {
        right.addActionListener(list);
    }
    
    void addLeftListener(ActionListener list) {
        left.addActionListener(list);
    }
    
    void addSkipListener(ActionListener list) {
        skip.addActionListener(list);
    }
}
